##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vdbench-raw
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "none"
  repl: "2"
  priority_io: "high"
  io_profile: "db_remote"
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdbench-raw01
spec:
  storageClassName: vdbench-raw
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdbench-raw02
spec:
  storageClassName: vdbench-raw
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdbench-raw03
spec:
  storageClassName: vdbench-raw
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

